service: sqlserver-init-custom-resource
useDotenv: true

provider:
  name: aws
  runtime: java11
  memorySize: 1024
  timeout: 60
  region: us-west-2
  deploymentBucket:
    name: ${env:BUCKET}
    serverSideEncryption: "AES256"
  logRetentionInDays: 7
  iam:
    deploymentRole: "arn:aws:iam::${env:ACCOUNT}:role/cloudformation/deployer/cloudformation-deployer"
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetResourcePolicy
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            - secretsmanager:ListSecretVersionIds
            - secretsmanager:ListSecret
          Resource:
            - "*"
  stackTags:
    Creator: serverless
    Environment: ${opt:stage}
    Project: ${self:service}
    Team: platform
    Visibility: internal
  vpc:
    subnetIds:
      - ${env:SUBNET_ID}
    securityGroupIds:
      - !GetAtt LambdaSg.GroupId
  lambdaHashingVersion: 20201221

functions:
  InitSqlServerDatabase:
    handler: com.dwolla.sqlserver.init.SqlServerDatabaseInitHandler
    package:
      artifact: ${env:DATABASE_ARTIFACT_PATH}

package:
  individually: true

resources:
  Resources:
    LambdaSg:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Traffic source security group for ${opt:stage} sqlserver-init-lambda
        VpcId:
          Fn::ImportValue: ${opt:stage}VpcId
        Tags:
          - Key: SecurityGroupType
            Value: TrafficSource
  Description: "CloudFormation custom resources for initializing Sql Server databases and users"
  Outputs:
    InitSqlServerDatabaseFunction:
      Description: Database initialization Lambda Function Service Token
      Value:
        'Fn::GetAtt': [InitSqlServerDatabaseLambdaFunction, Arn]
      Export:
        Name: ${self:service}:${opt:stage}:InitSqlServerDatabaseArn
    InitSqlServerDatabaseSg:
      Description: Secrutiy group attached to database initialization Lambda Function
      Value:
        !GetAtt LambdaSg.GroupId
      Export:
        Name: ${self:service}:${opt:stage}:InitSqlServerDatabaseSgId
